import React, { useState } from 'react';
import { Breadcrumb, Table } from '../../components/Tables/Tables';
import { SearchBar, FilterPlaceholder } from '../../components/Forms/Forms';
import { Modal } from '../../components/Modal/Modal';
import { FiPlus } from 'react-icons/fi';

export const Reports: React.FC = () => {
  const [modalOpen, setModalOpen] = useState(false);
  const [searchVal, setSearchVal] = useState('');
  const [filterVal, setFilterVal] = useState('All Statuses');

  const breadcrumbItems = [
    { label: 'TransitOps', href: '/' },
    { label: 'Reports', active: true }
  ];

  const columns = [
    { header: 'Report ID', accessor: 'reportId' },
    { header: 'Report Name', accessor: 'reportName' },
    { header: 'Type', accessor: 'type' },
    { header: 'Generated By', accessor: 'generatedBy' },
    { header: 'Date Created', accessor: 'dateCreated' },
    { header: 'Format', accessor: 'format' }
  ];

  return (
    <div className="space-y-6">
      {/* Top Breadcrumb and Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <Breadcrumb items={breadcrumbItems} />
          <h2 className="text-xl font-bold text-slate-800">Analytics Reports</h2>
        </div>
        <button
          onClick={() => setModalOpen(true)}
          className="flex items-center justify-center space-x-2 px-4 py-2.5 text-sm font-semibold text-white bg-blue-600 hover:bg-blue-700 active:bg-blue-800 rounded-xl transition duration-150 shadow-sm shadow-blue-200"
        >
          <FiPlus className="w-4 h-4" />
          <span>Generate Report</span>
        </button>
      </div>

      {/* Filter and Search Bar Row */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 bg-white border border-slate-100 rounded-2xl shadow-sm">
        <SearchBar 
          placeholder="Search report names, types..." 
          value={searchVal}
          onChange={setSearchVal}
        />
        <FilterPlaceholder 
          options={['All Formats', 'PDF', 'XLSX', 'CSV']}
          selected={filterVal}
          onSelect={setFilterVal}
        />
      </div>

      {/* Empty Table */}
      <Table
        columns={columns}
        emptyStateTitle="No analytical reports compiled"
        emptyStateDescription="Synthesize fuel usage sheets, fleet load reports, driver performance tables, or operations statistics logs."
        actionLabel="Compile Report"
        onActionClick={() => setModalOpen(true)}
      />

      {/* Generate Report Modal Placeholder */}
      <Modal isOpen={modalOpen} onClose={() => setModalOpen(false)} title="Generate Analytical Compilation">
        <div className="space-y-4">
          <p className="text-sm text-slate-500">
            Define report metrics range, select system parameters, filter data points, and select export format configurations.
          </p>
          <div className="space-y-3 p-4 bg-slate-50 border border-slate-100 rounded-xl">
            <div className="w-full h-8 bg-slate-200 rounded animate-pulse"></div>
            <div className="w-5/6 h-8 bg-slate-200 rounded animate-pulse"></div>
          </div>
          <div className="flex justify-end space-x-2 pt-4">
            <button 
              onClick={() => setModalOpen(false)}
              className="px-4 py-2 text-sm font-medium text-slate-500 bg-slate-100 hover:bg-slate-200 rounded-xl transition"
            >
              Cancel
            </button>
            <button 
              onClick={() => setModalOpen(false)}
              className="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-xl shadow-sm transition"
            >
              Compile
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
};
