import React, { useState, useEffect } from 'react';
import { Breadcrumb, Table } from '../../components/Tables/Tables';
import { SearchBar, FilterPlaceholder } from '../../components/Forms/Forms';
import { Modal } from '../../components/Modal/Modal';
import { api } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { FiPlus } from 'react-icons/fi';

export const Reports: React.FC = () => {
  const { user } = useAuth();
  const [reportsList, setReportsList] = useState<any[]>([]);
  const [modalOpen, setModalOpen] = useState(false);
  const [searchVal, setSearchVal] = useState('');
  const [filterVal, setFilterVal] = useState('All Formats');

  // Form Fields
  const [reportName, setReportName] = useState('');
  const [reportType, setReportType] = useState('fuel-efficiency');
  const [reportFormat, setReportFormat] = useState('CSV');

  // Submit states
  const [formSubmitting, setFormSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [formSuccess, setFormSuccess] = useState<string | null>(null);

  const breadcrumbItems = [
    { label: 'TransitOps', href: '/' },
    { label: 'Reports', active: true }
  ];

  const columns = [
    { header: 'Report ID', accessor: 'id' },
    { header: 'Report Name', accessor: 'reportName' },
    { header: 'Type', accessor: 'type' },
    { header: 'Generated By', accessor: 'generatedBy' },
    { header: 'Date Created', accessor: 'dateCreated' },
    { header: 'Format', accessor: 'format' }
  ];

  // Load persisted compilations
  useEffect(() => {
    const saved = localStorage.getItem('transitops_reports_list');
    if (saved) {
      try {
        setReportsList(JSON.parse(saved));
      } catch (err) {
        console.error('Failed reading reports list cache:', err);
      }
    } else {
      // Seed initial mock list if needed, or leave empty. Prompt says: "REMOVE all placeholder data. Do not use mock data."
      // So we start with empty array!
      setReportsList([]);
    }
  }, []);

  const saveReports = (list: any[]) => {
    setReportsList(list);
    localStorage.setItem('transitops_reports_list', JSON.stringify(list));
  };

  const handleOpenAddModal = () => {
    setReportName('');
    setReportType('fuel-efficiency');
    setReportFormat('CSV');
    setFormError(null);
    setFormSuccess(null);
    setModalOpen(true);
  };

  const handleCompileReport = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);
    setFormSuccess(null);
    setFormSubmitting(true);

    try {
      // 1. Trigger CSV download from backend
      const response = await api.get(`/reports/export?report=${reportType}`, {
        responseType: 'blob'
      });

      // Construct file download link
      const blob = new Blob([response.data], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `transitops-${reportType}-report.csv`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);

      // 2. Add compilation record to local list
      const newReport = {
        id: `REP-${Math.floor(1000 + Math.random() * 9000)}`,
        reportName: reportName || `${reportType.replace('-', ' ').toUpperCase()} compilation`,
        type: reportType.toUpperCase().replace('-', ' '),
        typeKey: reportType,
        generatedBy: user?.name || 'Administrator',
        dateCreated: new Date().toISOString(),
        format: reportFormat,
        status: 'Paid' // map to Paid to match badge style
      };

      const updated = [newReport, ...reportsList];
      saveReports(updated);

      setFormSuccess('Report compiled and downloaded successfully!');
      setTimeout(() => {
        setModalOpen(false);
      }, 1500);

    } catch (err: any) {
      setFormError(err.message || 'Failed compiling report metrics.');
    } finally {
      setFormSubmitting(false);
    }
  };

  const handleDownloadExisting = async (item: any) => {
    try {
      const response = await api.get(`/reports/export?report=${item.typeKey}`, {
        responseType: 'blob'
      });
      const blob = new Blob([response.data], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `transitops-${item.typeKey}-report.csv`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      alert('Failed to download report data.');
    }
  };

  const handleDeleteReport = (item: any) => {
    const updated = reportsList.filter(r => r.id !== item.id);
    saveReports(updated);
  };

  // Filter application
  const filteredReports = reportsList.filter((rep) => {
    const matchesSearch = 
      rep.reportName.toLowerCase().includes(searchVal.toLowerCase()) ||
      rep.type.toLowerCase().includes(searchVal.toLowerCase()) ||
      rep.id.toLowerCase().includes(searchVal.toLowerCase());
      
    const matchesFormat = 
      filterVal === 'All Formats' || 
      rep.format.toLowerCase() === filterVal.toLowerCase();

    return matchesSearch && matchesFormat;
  });

  return (
    <div className="space-y-6">
      {/* Top Breadcrumb and Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <Breadcrumb items={breadcrumbItems} />
          <h2 className="text-xl font-bold text-slate-800">Analytics Reports</h2>
        </div>
        <button
          onClick={handleOpenAddModal}
          className="flex items-center justify-center space-x-2 px-4 py-2.5 text-sm font-semibold text-white bg-blue-600 hover:bg-blue-700 active:bg-blue-800 rounded-xl transition duration-150 shadow-sm shadow-blue-200"
        >
          <FiPlus className="w-4 h-4" />
          <span>Generate Report</span>
        </button>
      </div>

      {/* Filter and Search Bar Row */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 bg-white border border-slate-100 rounded-2xl shadow-sm">
        <SearchBar 
          placeholder="Search report names, types..." 
          value={searchVal}
          onChange={setSearchVal}
        />
        <FilterPlaceholder 
          options={['All Formats', 'CSV']}
          selected={filterVal}
          onSelect={setFilterVal}
        />
      </div>

      {/* Empty Table / Reports Table */}
      <Table
        columns={columns}
        data={filteredReports}
        emptyStateTitle="No analytical reports compiled"
        emptyStateDescription="Synthesize fuel usage sheets, fleet load reports, driver performance tables, or operations statistics logs."
        actionLabel="Compile Report"
        onActionClick={handleOpenAddModal}
        onView={handleDownloadExisting}
        onDelete={handleDeleteReport}
        totalEntries={filteredReports.length}
        pageSize={filteredReports.length}
        totalPages={1}
        page={1}
      />

      {/* Generate Report Modal */}
      <Modal isOpen={modalOpen} onClose={() => !formSubmitting && setModalOpen(false)} title="Generate Analytical Compilation">
        <form onSubmit={handleCompileReport} className="space-y-4">
          {formError && <div className="p-3 bg-rose-50 text-rose-600 rounded-xl text-xs">{formError}</div>}
          {formSuccess && <div className="p-3 bg-emerald-50 text-emerald-600 rounded-xl text-xs">{formSuccess}</div>}

          <div>
            <label className="text-[10px] uppercase font-bold text-slate-400 block mb-1">Report Name</label>
            <input required placeholder="Fuel Efficiency Analysis Q3" value={reportName} onChange={e => setReportName(e.target.value)} className="block w-full border border-slate-200 text-slate-700 bg-white rounded-xl px-3 py-2 text-sm focus:outline-none" />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-[10px] uppercase font-bold text-slate-400 block mb-1">Select Metrics Category</label>
              <select value={reportType} onChange={e => setReportType(e.target.value)} className="block w-full border border-slate-200 text-slate-700 bg-white rounded-xl px-3 py-2 text-sm focus:outline-none">
                <option value="fuel-efficiency">Fuel Efficiency</option>
                <option value="utilization">Fleet Utilization</option>
                <option value="operational-cost">Operational Cost</option>
                <option value="roi">Vehicle ROI</option>
              </select>
            </div>
            <div>
              <label className="text-[10px] uppercase font-bold text-slate-400 block mb-1">Export Format</label>
              <select value={reportFormat} onChange={e => setReportFormat(e.target.value)} className="block w-full border border-slate-200 text-slate-700 bg-white rounded-xl px-3 py-2 text-sm focus:outline-none">
                <option>CSV</option>
              </select>
            </div>
          </div>

          <div className="flex justify-end space-x-2 pt-4 border-t border-slate-100">
            <button 
              type="button"
              disabled={formSubmitting}
              onClick={() => setModalOpen(false)}
              className="px-4 py-2 text-sm font-medium text-slate-500 bg-slate-100 hover:bg-slate-200 rounded-xl transition"
            >
              Cancel
            </button>
            <button 
              type="submit"
              disabled={formSubmitting}
              className="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-xl shadow-sm transition"
            >
              {formSubmitting ? 'Compiling...' : 'Compile & Download'}
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
};
